# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "frontend"
target = "javascript"
version = "1.0.0"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "~> 4.0.0-rc.2"
styled = {path = "../../packages/styled"}

[dev-dependencies]
gleeunit = "~> 1.0"
