# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "frontend"
target = "javascript"
version = "1.0.0"

[javascript]
typescript_declarations = true

[dependencies]
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
grille_pain = {path = "../../packages/grille_pain"}
layout = {path = "../../packages/layout"}
lustre = ">= 4.1.8 and < 5.0.0"
lustre_http = ">= 0.5.2 and < 1.0.0"
plinth = ">= 0.2.0 and < 1.0.0"
sketch = ">= 2.0.0 and < 3.0.0"
tardis = {path = "../../../tardis"}

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
