name = "radiate"
version = "0.3.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Hot reloading while in development for Gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
repository = {type = "github", user = "pta2002", repo = "gleam-radiate"}
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
filespy = ">= 0.4.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
